export interface Paciente {
    clave?: number;
    nombre?: string;
    sexo?: boolean;
    fechaDeNacimiento?: Date | null;
    lugarDir?: string;
    responsable?: string;
    puesto?: string;
    empresa?: string;
    religion?: string;
    referencia?: string;
    rfc?: string;
    docPref?: string;
    recall?: boolean;
    frecRecall?: string;
    reciboNom?: string;
    reciboDir?: string;
    ultCita?: Date | null;
    ultProf?: Date | null;
    ttrata?: number;
    tprof?: number;
    puntual?: string;
    paga?: string;
    banco?: boolean;
    cualBanco?: number;
    comentarios?: string;
    incluye?: boolean;
    nºcuenta?: string;
    beneficiario?: string;
    memoInicio?: Date | null;
    memoFin?: Date | null;
    ingresos?: string;
    clasificación?: string;
    email?: string;
    eName?: string;
    motivo?: string;
    tema: string;
    tipoEvento?: string;
    start?: Date | null;
    finish?: Date | null;
    izq?: number;
    arriba?: number;
    ancho?: number;
    alto?: number;
    prop?: number;
    local?: string;
    privado?: string;
    expediente?: string;
    depto?: string;
}
