export interface Paciente {
  id: number;
  clave: number;
  fechaDeNacimiento: string;
  sexo: string;
  estadoCivil: string;
  ocupacion: string;
  domicilio: string;
  poblacion: string;
  telefono: string;
  email: string | null;
  nombreDelEsposo: string | null;
  edadDelEsposo: string | null;
  ocupacionEsposo: string | null;
  referencia: string;
  diabetes: string;
  hipertension: string;
  trombosis: string;
  cardiopatias: string;
  cancer: string;
  enfermedadesGeneticas: string;
  otraEnfermedad: string;
  inmunizaciones: string;
  alcoholismo: string;
  tabaquismo: string;
  tabaquismoPasivo: string;
  drogasOmedicamentos: string;
  grupoSanguineo: string;
  propiasDeLaInfancia: string;
  rubeola: string;
  amigdalitis: string;
  bronquitis: string;
  bronconeumonia: string;
  hepatitisViralTipo: string;
  parasitosis: string;
  toxoplasmosis: string;
  citomegalovirus: string;
  herpes: string;
  clamydiasis: string;
  hiv: string;
  sifilis: string;
  micosis: string;
  eip: string;
  diabetesMellitus: string;
  otrasEndocrinas: string;
  nefropatias: string;
  digestivas: string;
  neurologicas: string;
  hematologicas: string;
  tumores: string;
  condilomatosis: string;
  displasias: string;
  alergia: string;
  nombre: string;
  fechaConsulta: string;
  fechaUltimaConsulta: string;
  hipertensionFamiliar: string;
  cardiopatiaFamiliar: string;
  otraEnfermedadPersonal: string;
}